name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '*.py'
      - 'requirements.txt'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '*.py'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        